FROM node:20-alpine
RUN npm install -g genieacs@1.2.9 --omit=dev
RUN mkdir -p /var/log/genieacs
EXPOSE 7547 7557 7567
CMD ["sh", "-c", "genieacs-cwmp & genieacs-nbi & genieacs-fs & exec genieacs-ui"]
